inherit_from:
- https://relaxed.ruby.style/rubocop.yml

AllCops:
  Exclude:
    - __test/**
    - test/**
    - bin/**
    - spec/**/*
    - config/**/*
    - db/**/*
    - Gemfile
    - "*.gemspec"
    - bundler/**/*
    - vendor/bundle/**/* # travis with --deployment
  TargetRubyVersion: 2.5

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'

Style/FormatString:
  EnforcedStyle: percent

Style/FrozenStringLiteralComment:
  Enabled: false

Style/WordArray:
  Enabled: true
  MinSize: 3

Style/EmptyMethod:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Style/PerlBackrefs:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Style/SpecialGlobalVars:
  Enabled: true

Style/Alias:
  Enabled: true

Style/BeginBlock:
  Enabled: true

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - cn

Metrics/BlockLength:
  Enabled: false
